/*
 * Copyright (C) 2024 Rick Busarow
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

buildscript {
  dependencies {
    // This resolves to the gradle-plugin artifact generated by the delegate build.
    // Now that it's in the build classpath, it can be applied by its ID in subprojects.
    classpath("com.rickbusarow.matrix:matrix-gradle-plugin")
  }
}

plugins {
  id("root")
  alias(libs.plugins.moduleCheck)
  alias(libs.plugins.buildconfig)
  id("com.rickbusarow.matrix")
}

matrices {

  matrix("deps") {

    val kotlin = paramGroup("kotlin") { setOf("1.5.31", libs.versions.kotlin.get()) }
    val gradle = paramGroup("gradle") { setOf("7.0", "8.5", gradle.gradleVersion) }
    val other = paramGroup("other") { setOf("1.0.0", "2.0.0") }

    exclude(kotlin to "1.5.31", gradle to "7.0")
  }
}

moduleCheck {
  deleteUnused = true
  checks.sortDependencies = true
}
