name: Label Pull Request
run-name: Label Pull Request on ${{ github.ref-name }}

on:
  # `pull_request_target` makes it so that the action is run against the configuration in the
  # destination branch, instead of the one in the PR branch.
  - pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      # see https://github.com/actions/labeler
      - uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7
        with:
          configuration-path: ".github/labeler-config.yml"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          # automatically remove labels if the PR changed and made them invalid
          sync-labels: true
